import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "animate.css";
import "../styles/globals.css";
import Navbanner from "@/components/common/Navbanner";
import Header from "@/components/common/header/Header";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    default: "Online Store",
    template: "Online Store | %s",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Navbanner />
        <div className="max-w-6xl mx-auto">
          <Header />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
